apiVersion: v1
kind: Service
metadata:
  name: {{ include "jdy-data-sync.fullname" . }}-app-svc
  labels:
    {{- include "jdy-data-sync.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jdy-data-sync.app.selectorLabels" . | nindent 4 }}