apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.internalService.name }} # MUST match the serviceName in StatefulSet
  labels:
    {{- include "jdy-data-sync.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mysql.internalService.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "jdy-data-sync.mysql.selectorLabels" . | nindent 4 }}