apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jdy-data-sync.fullname" . }}-mysql
  labels:
    {{- include "jdy-data-sync.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.mysql.internalService.name }} # Headless service name
  replicas: 1
  selector:
    matchLabels:
      {{- include "jdy-data-sync.mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jdy-data-sync.mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.envSecretName }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes: []
  {{- if .Values.mysql.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}
        {{- if .Values.mysql.persistence.storageClass }}
        storageClassName: {{ .Values.mysql.persistence.storageClass }}
        {{- end }}
  {{- end }}